### ISSUE TITLE
Prefix commands 

### ISSUE THREAD

**Issue by Excriyin** [CASPERg267/GF-Music#6]
2022-11-24 03:57:16 [error] [messageCreate] Something went wrong while running a command **[TypeError: "command_name" is not typeof string]** getting this error everytime i run a prefix command

**Comment by Excriyin** [comment]
another error in slash command help 
rror [GuildChannelResolve]: Could not resolve channel to a guild channel.
    at GuildMember.permissionsIn (/home/container/node_modules/discord.js/src/structures/GuildMember.js:304:25)
    at module.exports (/home/container/events/guild/interactionCreate.js:94:43)
    at gfMusicClient.emit (node:events:394:28)
    at InteractionCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/InteractionCreate.js:81:12)
    at Object.module.exports [as INTERACTION_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:480:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:320:10)
    at callListener (/home/container/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:209:9)
Emitted 'error' event on gfMusicClient instance at:
    at emitUnhandledRejectionOrErr (node:events:254:10)
    at processTicksAndRejections (node:internal/process/task_queues:85:21) {
  code: 'GuildChannelResolve'

**Comment by CASPERg267** [comment]
![image](https://user-images.githubusercontent.com/74456381/203692407-6fb09405-bc15-48f5-8a79-425535c58c8e.png)
any idea how can i produce these errors?

**Comment by Excriyin** [comment]
thats odd, why doesnt it work for me?

**Comment by Excriyin** [comment]
for some reason i just keep getting this error  
2022-11-24 04:29:18 [error] [messageCreate] Something went wrong while running a command **[TypeError: "command_name" is not typeof string]**
i dont know how its working for you 

and this error for help slash command 2022-11-24 04:29:46 [error] [Anti Crash Module] Uncaught Exception, ({"code":"GuildChannelResolve"})

**Comment by CASPERg267** [comment]
> for some reason i just keep getting this error 2022-11-24 04:29:18 [error] [messageCreate] Something went wrong while running a command **[TypeError: "command_name" is not typeof string]** i dont know how its working for you
> 
> and this error for help slash command 2022-11-24 04:29:46 [error] [Anti Crash Module] Uncaught Exception, ({"code":"GuildChannelResolve"}) - plus the application dont respond

i ve been able to reproduce the 2nd error and fixed it, for the first error, did you change something in the code?
or add "console.error(e.stack)" inside catch block so we can find exactly where error comes from?

**Comment by Excriyin** [comment]
i havent changed anything in code other than editing config.js

**Comment by Excriyin** [comment]
Is it because maybe a statford problem,  because everytime the bot is online, on the site it says its offline after a few minutes

**Comment by CASPERg267** [comment]
Please if you have more information about producing this error feel free to let me know, i ll be more than happy to fix it
will leave this open if someone runs into the same error.

**Comment by Excriyin** [comment]
> Please if you have more information about producing this error feel free to let me know, i ll be more than happy to fix it will leave this open if someone runs into the same error.

Maybe its a package problem? what node and npm  did you use to install the packages ?

**Comment by CASPERg267** [comment]
@Excriyin can you test last pushes and see if error persists?

**Comment by Excriyin** [comment]
it works now thank you
