### ISSUE TITLE
Lyrics issue again

### ISSUE THREAD

**Issue by Excriyin** [CASPERg267/GF-Music#7]
When running the command, it says couldnt find the lyrics of the song, and in console it displays: 
TypeError: Cannot read properties of null (reading 'length')
    at Object.run (/home/container/commands/music/lyrics.js:43:20)
    at module.exports (/home/container/events/guild/messageCreate.js:117:15)
    at gfMusicClient.emit (node:events:394:28)
    at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:28:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:480:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:320:10)
    at callListener (/home/container/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:209:9) Promise {
  <rejected> TypeError: Cannot read properties of null (reading 'length')
      at Object.run (/home/container/commands/music/lyrics.js:43:20)
      at module.exports (/home/container/events/guild/messageCreate.js:117:15)
      at gfMusicClient.emit (node:events:394:28)
      at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:28:14)
      at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
      at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
      at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:480:22)
      at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:320:10)
      at callListener (/home/container/node_modules/ws/lib/event-target.js:290:14)
      at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:209:9)
}

**Comment by Excriyin** [comment]
noted, this is for both for commands, and slash commands

**Comment by CASPERg267** [comment]
i assume lyrics bug fixed [but](https://github.com/zyrouge/node-genius-lyrics/issues/35)

**Comment by CASPERg267** [comment]
@Excriyin  can you test with node version 16? it should work fine as it works for me on node v16

**Comment by Excriyin** [comment]
thank you it works now
